# Generated by Django 4.1.3 on 2023-01-12 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_one', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='Product_shop/static/icons')),
                ('base64', models.TextField()),
                ('name_unit', models.CharField(max_length=50)),
                ('count', models.PositiveIntegerField()),
                ('prace_all', models.DecimalField(decimal_places=2, max_digits=7)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product_shop.category')),
            ],
        ),
    ]
