# Generated by Django 4.1.3 on 2023-01-12 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product_shop', '0001_initial'),
        ('User_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product_shop.icon'),
        ),
        migrations.AlterField(
            model_name='order',
            name='prace_all',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
    ]
