# Generated by Django 4.1.5 on 2023-01-15 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product_shop_2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_one', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.CharField(max_length=100)),
                ('base64', models.TextField()),
                ('name_unit', models.CharField(max_length=50)),
                ('count', models.PositiveIntegerField(blank=True, default=1)),
                ('prace_all', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product_shop_2.category')),
                ('icon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product_shop_2.icon')),
            ],
        ),
    ]
