# Generated by Django 4.1.5 on 2023-01-18 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price_one',
            new_name='price',
        ),
    ]
